# fly.toml app configuration file generated for local-transfer on 2025-03-22T15:48:41Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'local-transfer'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.ports]]
handlers = ["http"]
port = 80
force_https = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
